# Generated by Django 5.2.1 on 2025-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='eventname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
