# Generated by Django 5.2.1 on 2025-05-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_eventregistration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
